import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions — intelliDocs",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-r from-rose-100 to-teal-100">
      <div className="max-w-3xl mx-auto px-6 py-12">

        {/* Header */}
        <Link href="/" className="flex items-center gap-2 mb-10">
          <div className="w-8 h-8 rounded-lg overflow-hidden bg-white shadow-sm flex items-center justify-center">
            <Image src="/Logo.svg" alt="intelliDocs" width={26} height={26} className="object-contain" />
          </div>
          <span className="font-bold text-gray-800 tracking-tight">intelliDocs</span>
        </Link>

        <div className="bg-white/70 backdrop-blur-sm rounded-2xl p-8 shadow-sm border border-white/80">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms &amp; Conditions</h1>
          <p className="text-sm text-gray-500 mb-8">Last updated: March 2026</p>

          <div className="space-y-7 text-gray-700 text-sm leading-relaxed">

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
              <p>By accessing or using intelliDocs (&quot;the Service&quot;), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the Service. These terms apply to all users of the Service.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">2. Description of Service</h2>
              <p>intelliDocs is an AI-powered document chat platform that allows users to upload PDF documents and interact with their content through a conversational AI interface. The Service is provided for personal and professional informational purposes only.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">3. User Accounts</h2>
              <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately at <a href="mailto:vinitrajsingh5555@gmail.com" className="text-blue-600 hover:underline">vinitrajsingh5555@gmail.com</a> of any unauthorized use of your account.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">4. Acceptable Use</h2>
              <p className="mb-2">You agree not to use the Service to:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Upload documents containing illegal, harmful, or infringing content</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Attempt to reverse-engineer, hack, or disrupt the Service</li>
                <li>Upload malware, viruses, or malicious code</li>
                <li>Infringe on the intellectual property rights of others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">5. Uploaded Content</h2>
              <p>You retain ownership of all documents you upload. By uploading content, you grant intelliDocs a limited, non-exclusive license to process and store the content solely to provide the Service. You are solely responsible for ensuring you have the right to upload any document.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">6. AI-Generated Responses</h2>
              <p>Responses generated by the AI are based on the content of your uploaded documents and are provided for informational purposes only. intelliDocs does not guarantee the accuracy, completeness, or reliability of AI-generated responses. You should not rely on them as professional legal, medical, financial, or other specialist advice.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">7. Intellectual Property</h2>
              <p>The Service, including its design, code, and branding, is the intellectual property of Vinit Raj Singh. You may not copy, modify, distribute, or create derivative works without explicit written permission.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">8. Limitation of Liability</h2>
              <p>To the fullest extent permitted by law, intelliDocs and its creator shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to data loss or inaccurate AI responses.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">9. Service Availability</h2>
              <p>We do not guarantee uninterrupted or error-free access to the Service. We reserve the right to modify, suspend, or discontinue the Service at any time without prior notice.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">10. Changes to Terms</h2>
              <p>We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes your acceptance of the revised Terms. We encourage you to review this page periodically.</p>
            </section>

            <section>
              <h2 className="text-base font-semibold text-gray-900 mb-2">11. Contact</h2>
              <p>For any questions regarding these Terms, please contact: <a href="mailto:vinitrajsingh5555@gmail.com" className="text-blue-600 hover:underline">vinitrajsingh5555@gmail.com</a></p>
            </section>

          </div>
        </div>

        <div className="text-center mt-6 text-xs text-gray-500">
          <Link href="/" className="hover:text-gray-700 transition-colors">← Back to intelliDocs</Link>
        </div>
      </div>
    </div>
  );
}
